language: python
python:
  - "3.7"
# install: pip install -r requirements.txt
# - "pypy3" # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
services:
  - postgresql
env:
  global:
    - NODE_ENV=test
    - JWT_SECRET_KEY=prfhdfdh
install:
  - pip install pipenv
  - pipenv install
# before_script:
#   - psql -c "CREATE USER tolumide WITH PASSWORD null;" -U postgres
#   - psql -c 'create database errorswag;' -U postgres
#   - psql -U postgres -d errorswag -c 'CREATE EXTENSION pg_trgm'

# create db
# script to run migration
# command to run tests
script: pytest --cov=src
after_successs: coveralls
